CREATE TABLE exercises (
    exercise_id TEXT PRIMARY KEY,
    name_et TEXT NOT NULL,
    name_en TEXT NOT NULL,
    aliases_et TEXT,
    aliases_en TEXT,
    movement_pattern_primary TEXT NOT NULL,
    movement_pattern_secondary TEXT,
    training_function TEXT NOT NULL,
    biomechanical_function TEXT NOT NULL,
    exercise_type TEXT NOT NULL,
    equipment_primary TEXT NOT NULL,
    equipment_secondary TEXT,
    body_position TEXT,
    bilateral_unilateral TEXT,
    open_closed_chain TEXT,
    primary_muscles TEXT NOT NULL,
    secondary_muscles TEXT NOT NULL,
    stabilizers TEXT NOT NULL,
    direct_load_weights TEXT,
    indirect_load_weights TEXT,
    muscle_length_profile TEXT,
    beginner_suitability INTEGER,
    intermediate_suitability INTEGER,
    advanced_suitability INTEGER,
    technical_complexity INTEGER,
    learning_difficulty INTEGER,
    stability_requirement INTEGER,
    coordination_requirement INTEGER,
    mobility_requirement INTEGER,
    fatigue_cost INTEGER,
    time_cost INTEGER,
    setup_time TEXT,
    default_sets TEXT,
    default_reps TEXT,
    default_rest_seconds TEXT,
    tempo_numeric TEXT,
    tempo_text_et TEXT,
    instructions_et TEXT NOT NULL,
    breathing_et TEXT NOT NULL,
    common_mistakes_et TEXT NOT NULL,
    coaching_cues_et TEXT NOT NULL,
    what_to_feel_et TEXT,
    contraindications TEXT,
    caution_flags TEXT,
    alternatives TEXT NOT NULL,
    progression_candidates TEXT,
    regression_candidates TEXT,
    substitution_group TEXT,
    evidence_ids TEXT,
    client_visible BOOLEAN DEFAULT 1,
    status TEXT DEFAULT 'draft',
    version TEXT DEFAULT '1.0'
);
